== __Abstract in English__

.__**English speaking readers, you may click here** to read what this specification is about and how you may read it.__
[%collapsible]
====
__This specification, CCCEV-AP-NO, is the Norwegian application profile of https://github.com/SEMICeu/CCCEV/[EUs Core Criterion and Core Evidence Vocabulary (CCCEV) &#x29C9;, window="_blank", role="ext-link"]. It specifies how to describe criteria and requirements in structured form, and how to make the descriptions available in machine-readable RDF-based formats.__ 

__This specification is primarily not meant to be used alone. It supplements the https://data.norge.no/specification/cpsv-ap-no#_abstract_in_english["Norwegian specification for description of services and events, CPSV-AP-NO &#x29C9;"", window="_blank", role="ext-link"], which is the Norwegian application profile of https://github.com/SEMICeu/CPSV-AP/[EUs Core Public Service Vocabulary Application Profile (CPSV-AP) &#x29C9;, window="_blank", role="ext-link"]__.

__The specification is mainly in Norwegian. However, in <<del2, Chap. 3>> which requires a certain level of knowledge in RDF, the specification of the classes and properties is in both Norwegian and English. Norwegian extensions (compared to CCCEV) are also documented as "Note" to the class/property in concern.__
====