name: Build adocs and publish v1 to production

permissions:
  contents: read

on:
  push:
    branches:
      - v1
    paths:
      - docs/**
  workflow_dispatch:

jobs:
  upload-files-to-production:
    name: Upload specification to static-rdf-server
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-upload-files.yaml@main
    with:
      ref: v1
      program_html: |
        asciidoctor -D docs -o index.html -a lang=nb docs/main.adoc
      program_pdf: |
        asciidoctor-pdf -D docs -o files/cccev-ap-no.pdf -a lang=nb docs/main.adoc
      program_pdf_continue_on_error: true
      host: https://data.norge.no
      ontology: cccev-ap-no
      ontology-type: specification
      files: |
        docs/index.html text/html nb
        docs/files/cccev-ap-no.pdf application/pdf nb files/cccev-ap-no.pdf
        docs/images/Digdir.png image/png nb images/Digdir.png
        docs/images/CCCEV-AP-NO-forenklet-fremstilling.png image/png nb images/CCCEV-AP-NO-forenklet-fremstilling.png
        docs/images/CCCEV-AP-NO-klasser.png image/png nb images/CCCEV-AP-NO-klasser.png
        docs/images/FigurEksempelDokumentasjonskrav.png image/png nb images/FigurEksempelDokumentasjonskrav.png
        docs/images/FigurEksempelDokumentasjonskrav2.png image/png nb images/FigurEksempelDokumentasjonskrav2.png
        docs/images/KlassenBegrensning.png image/png nb images/KlassenBegrensning.png
        docs/images/KlassenDokumentasjonstypeliste.png image/png nb images/KlassenDokumentasjonstypeliste.png
        docs/images/KlassenInformasjonsbegrep.png image/png nb images/KlassenInformasjonsbegrep.png
        docs/images/KlassenInformasjonskrav.png image/png nb images/KlassenInformasjonskrav.png
        docs/images/KlassenKrav.png image/png nb images/KlassenKrav.png
        docs/images/KlassenKriterium.png image/png nb images/KlassenKriterium.png
        docs/images/KlassenReferanserammeverk.png image/png nb images/KlassenReferanserammeverk.png
    secrets:
      STATIC_RDF_SERVER_API_KEY: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
